- deploy/kubernetes/sloth.yaml
Since sloth doesn't use its port for anything else than exposing metrics, there is no need to create a Service object and use ServiceMonitor when the same functionality can be accomplished with PodMonitor.
OT: Great project! :tada:
> deploy/kubernetes: move to PodMonitor

- CHANGELOG.md
- cmd/sloth/commands/generate.go
- cmd/sloth/commands/helpers.go
- cmd/sloth/commands/k8scontroller.go
- cmd/sloth/commands/validate.go
- internal/k8sprometheus/spec.go
- internal/k8sprometheus/spec_test.go
- internal/prometheus/sli_plugin.go
- internal/prometheus/sli_plugin_test.go
- internal/prometheus/spec.go
- internal/prometheus/spec_test.go
This change sets a cleaner way of obtaining SLI plugins and gives us the ability to make a hotreload of plugins in the future.
> Use dynamic plugin loader service that can be reloaded instead of a map

- CHANGELOG.md
- cmd/sloth/commands/k8scontroller.go
- go.mod
- go.sum
SLI plugins will work as always, except now we can load again all of them from the specified file paths when we want by:
- Making a POST request on the hot-reload HTTP address port and path (by default on `0.0.0.0:8082/-/reload`). 
- Sending a SIGHUP to the Sloth process.
This can be interesting using it alongside with [git-sync](https://github.com/kubernetes/git-sync) sidecar.
Examples:
- HTTP: `curl -XPOST http://127.0.0.1:8082/-/reload`.
- Signal: `kill -HUP 567040`.
> Add hot-reload support for SLI plugins (with webhook and SIGHUP)

- CHANGELOG.md
- README.md
- cmd/sloth/commands/generate.go
- cmd/sloth/commands/validate.go
- internal/k8sprometheus/spec.go
- internal/k8sprometheus/spec_test.go
- internal/openslo/spec.go
- internal/openslo/spec_test.go
- internal/prometheus/spec.go
- internal/prometheus/spec_test.go
This PR changes how we load the specs on the `validate` and `generate` commands. Before this, we would try loading every type as a chain of spec loaders. Now we instead infer the spec type before loading them.
- It should improve the performance because we don't try loading all the spec, just match some small precompiled regexes.
- The errors are cleaner because now we know that when a spec loader fails, is because is not a valid, not because is not of the type trying to load.
> Infer spec type on validate and generate commands, instead of using bruteforce by loading all of them as a chain of fallbacks

- deploy/kubernetes/sloth-with-common-plugins.yaml
An example that deploys Sloth on Kubernetes and uses [git-sync](https://github.com/kubernetes/git-sync) as a sidecar on the pod to sync https://github.com/slok/sloth-common-sli-plugins so sloth hot-reloads the plugins.
> Add Sloth with common plugins deploy example

- deploy/kubernetes/helm/Chart.yaml
- deploy/kubernetes/helm/tests/testdata/output/cluster_role_binding_custom.yaml
- deploy/kubernetes/helm/tests/testdata/output/cluster_role_binding_default.yaml
- deploy/kubernetes/helm/tests/testdata/output/cluster_role_custom.yaml
- deploy/kubernetes/helm/tests/testdata/output/cluster_role_default.yaml
- deploy/kubernetes/helm/tests/testdata/output/deployment_custom.yaml
- deploy/kubernetes/helm/tests/testdata/output/deployment_custom_no_extras.yaml
- deploy/kubernetes/helm/tests/testdata/output/deployment_default.yaml
- deploy/kubernetes/helm/tests/testdata/output/pod_monitor_custom.yaml
- deploy/kubernetes/helm/tests/testdata/output/pod_monitor_default.yaml
- deploy/kubernetes/helm/tests/testdata/output/sa_custom.yaml
- deploy/kubernetes/helm/tests/testdata/output/sa_default.yaml
First, thank you for the Sloth project! This kind of tool is sorely needed to take much of the toil out of generating SLO-based  metrics, visualizations, and alerts 😀 
We want to use the Helm deploy method and would love to stay in sync with upstream, but are running a 1.19 cluster at the moment.
```
score-sloth                       sloth                              False   Helm install failed: chart requires kubeVersion: >= 1.20.0 which is incompatible with Kubernetes v1.19.12-gke.2101   17h
```
This change would relax the chart's version restriction by a minor kube version. It seemed like this wouldn't be problematic, since CI already tests against kube 1.19?
https://github.com/slok/sloth/blob/3f0d37f2a184bb8560357c82bc51265ceac0bb7f/.github/workflows/ci.yaml#L69-L71
> Support deployment via Helm to kube 1.19 clusters

- deploy/kubernetes/helm/Chart.yaml
- deploy/kubernetes/helm/tests/testdata/output/cluster_role_binding_custom.yaml
- deploy/kubernetes/helm/tests/testdata/output/cluster_role_binding_default.yaml
- deploy/kubernetes/helm/tests/testdata/output/cluster_role_custom.yaml
- deploy/kubernetes/helm/tests/testdata/output/cluster_role_default.yaml
- deploy/kubernetes/helm/tests/testdata/output/deployment_custom.yaml
- deploy/kubernetes/helm/tests/testdata/output/deployment_custom_no_extras.yaml
- deploy/kubernetes/helm/tests/testdata/output/deployment_default.yaml
- deploy/kubernetes/helm/tests/testdata/output/pod_monitor_custom.yaml
- deploy/kubernetes/helm/tests/testdata/output/pod_monitor_default.yaml
- deploy/kubernetes/helm/tests/testdata/output/sa_custom.yaml
- deploy/kubernetes/helm/tests/testdata/output/sa_default.yaml
Helm deployment will fail to any GKE or EKS cluster, due to:
https://github.com/helm/helm/issues/3810
Example error message:
```
Helm install failed: chart requires kubeVersion: >= 1.19.0 which is incompatible with Kubernetes 1.20.9-gke.1001
```
GKE and EKS identify their kube server versions using semver's "pre-release" syntax (ex. GKE might report a version string like `1.20.8-gke.2100`).
> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.
> https://semver.org/spec/v2.0.0.html
Helm's semver library implements the semver spec by failing to match pre-release versions unless the constraint explicitly allows pre-releases (ex. the constraint `>=1.19.0-0`).
> This includes …
> Fix/add Helm deploy support for GKE and EKS

- deploy/kubernetes/helm/sloth/values.yaml
Seems that Helm chart releaser checks changes from the latest tag, so if we change the chart at the same time that we tag the release and the CI us run, this will not detect changes. So we are poking to force the chart release
> Poke helm chart to force release

- deploy/kubernetes/helm/sloth/Chart.yaml
- deploy/kubernetes/helm/sloth/templates/deployment.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/cluster_role_binding_custom.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/cluster_role_binding_default.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/cluster_role_custom.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/cluster_role_default.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/configmap_slo_config.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom_no_extras.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom_slo_config.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_default.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/pod_monitor_custom.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/pod_monitor_default.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/sa_custom.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/sa_default.yaml
- deploy/kubernetes/raw/sloth-with-common-plugins.yaml
- deploy/kubernetes/raw/sloth.yaml
This is a very simple typo fix in the heml chart, the string `extra-lables` -> `extra-labels`.
Updated the Chart version to `0.4.1` manually, but in case this is not needed please let me know and will revert it back
> Helm: fix typo from extra-lables to extra-labels

- CHANGELOG.md
- cmd/sloth/commands/generate.go
- cmd/sloth/commands/k8scontroller.go
- cmd/sloth/commands/validate.go
- internal/app/generate/prometheus.go
- internal/prometheus/recording_rules.go
- internal/prometheus/recording_rules_test.go
- scripts/examplesgen.sh
Fixes #241 
This PR adds a new flag (`--disable-optimized-rules`) on Kubernetes and CLI modes to disable full period optimized rules (e.g 30 day). If disabled the generated SLI recording rules will be like the rest.
> Allow disabling optimized recording rules for full period window

- CHANGELOG.md
- cmd/sloth/commands/generate.go
- scripts/examplesgen.sh
Fixes #252 
This PR adds support for SLO generation from a directory instead of a single file. The discovery is done automatically, Sloth will check if the input is a file or a directory, and based on that it will execute in single file mode or dir mode.
Also adds `--fs-exclude` and `--fs-include` as in the `validate` command.
The output files will be in the same structure as the input files.
```bash
sloth -p ./examples/plugins/ -i ./test-examples/ -o ./out-examples/
```
<details>
<summary>Input file tree</summary>
```text
./test-examples/
├── getting-started.yml
├── home-wifi.yml
├── k8s-getting-started.yml
├── k8s-home-wifi.yml
├── k8s-multifile.yml
├── kubernetes-apiserver.yml
├── l1
│   ├── getting-started.yml
│   ├── home-wifi.yml
│   ├── k8s-getting-started.yml
│   ├── …
```
> Add ability to generate from a directory by discovering SLOs and store generated rules on another directory

- deploy/kubernetes/helm/sloth/Chart.yaml
- deploy/kubernetes/helm/sloth/templates/deployment.yaml
- deploy/kubernetes/helm/sloth/tests/helm_chart_test.go
- deploy/kubernetes/helm/sloth/tests/testdata/input/custom.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/cluster_role_binding_custom.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/cluster_role_binding_default.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/cluster_role_custom.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/cluster_role_default.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/configmap_slo_config.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom_no_extras.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom_slo_config.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_default.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/pod_monitor_custom.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/pod_monitor_default.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/sa_custom.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/sa_default.yaml
- deploy/kubernetes/helm/sloth/values.yaml
Chart support for #259.
Also reduced the amount edits needed to test cases with a helm version bump. Hope that is appreciated.
Let me know if you'd prefer something like `extraArgs` instead of enumerating all arg options in chart. 
Will need a new docker release and a bit of testing as well
> Helm support for disabling optimized flag

- deploy/kubernetes/helm/sloth/Chart.yaml
- deploy/kubernetes/helm/sloth/templates/pod-monitor.yaml
```yaml
metrics:
prometheusLabels:
release: prometheus-operator
app: kube-prometheus-stack
```
When adding multiple labels like example above, indentation is getting screwed. Resulting in this:
```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
name: ep-sloth
namespace: sloth-test
labels:
helm.sh/chart: sloth-0.5.0
app.kubernetes.io/managed-by: Helm
app: sloth
app.kubernetes.io/name: sloth
app.kubernetes.io/instance: ep-sloth
app: kube-prometheus-stack
release: prometheus-operator <<------
spec:
selector:
matchLabels:
app: sloth
app.kubernetes.io/name: sloth
app.kubernetes.io/instance: ep-sloth
podMetricsEndpoints:
- port: metrics
```
This fixes this behavior.
> Add nindent to prometheusLabels

- deploy/kubernetes/helm/sloth/Chart.yaml
- deploy/kubernetes/helm/sloth/templates/deployment.yaml
- deploy/kubernetes/helm/sloth/values.yaml
k8s.gcr.io is blocked in China. This commit makes `k8s.gcr.io/git-sync/git-sync` configurable in Helm values so it can be pulled from alternative repositories.
> Make git-sync image repo and tag configurable

- deploy/kubernetes/helm/sloth/templates/_helpers.tpl
- deploy/kubernetes/helm/sloth/templates/deployment.yaml
- deploy/kubernetes/helm/sloth/values.yaml
Why?
people who use private image repository that has security enabled, cant deploy sloth with helm ,
added the pull image secret to enable the use the sloth image on private repos for helm deployments
> feat: image repository secret lists added

- deploy/kubernetes/helm/sloth/templates/deployment.yaml
- deploy/kubernetes/helm/sloth/tests/helm_chart_test.go
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom_no_extras.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom_slo_config.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_default.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_securityContext.yaml
- deploy/kubernetes/helm/sloth/tests/values_test.go
- deploy/kubernetes/helm/sloth/values.yaml
What: Deployments can have security settings in their manifest on two levels: pod and container. However, there are some capabilities only configurable in one of the respective levels(https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#securitycontext-v1-core). This PR sets a default configuration for container securityContext, which drops all POSIX capabilities and denies privilege escalation and for pod securityContext adds user, group fsGroup and supplementalGroups and also denies root usage.
These are and should be standard settings in the context of Kubernetes. It also adds the possibility of running vault-injector in a Kubernetes environment without PSP (to be removed in v1.25 https://kubernetes.io/docs/concepts/security/pod-security-policy/), but with …
> feat: add securityContext for pod and container

- internal/prometheus/spec.go
When we use config files that has line ending with CRLF the sloth fails to recognise specs because of the regex rules.
This change allows sloth to recognize prometheus spec in CRLF files.
Fixes: https://github.com/slok/sloth/issues/406
> Allow spec files with CRLF

- deploy/kubernetes/helm/sloth/Chart.yaml
- deploy/kubernetes/helm/sloth/templates/deployment.yaml
There is an issue with the current deployment template yaml file when setting tolerations in the values.yaml file.
Setting the tolerations in the values.yaml file:
```
tolerations:
- key: "infra"
operator: "Equal"
value: "true"
effect: "NoSchedule"
```
Error message when deploying:
```
k apply -f sloth4.yaml -n sloth 
...
serviceaccount/sloth created
clusterrole.rbac.authorization.k8s.io/sloth created
clusterrolebinding.rbac.authorization.k8s.io/sloth created
Error from server (BadRequest): error when creating "sloth4.yaml": Deployment in version "v1" cannot be handled as a Deployment: strict decoding error: unknown field "spec.template.spec.containers[0].tolerations"
```
This PR fixes the deployment.yaml issue by moving the `tolerations` on the pod spec level.
> Tolerations fix for deployment template

- internal/app/generate/prometheus.go
- internal/app/generate/prometheus_test.go
- internal/k8sprometheus/storage.go
- internal/k8sprometheus/storage_test.go
- internal/storage/io/std_prometheus.go
- internal/storage/io/std_prometheus_test.go
- pkg/common/model/slo_prometheus.go
This will allow us being more flexible when adding features to final rule groups (e.g: intervals, overrides...).
Related to OSS-23
> Add a middle domain model for prom rules

- go.mod
solves issues with go downloading
https://stackoverflow.com/q/78519711
```
go: downloading go1.24 (linux/amd64)
go: download go1.24 for linux/amd64: toolchain not available
```
> fix: update go version go.mod

- deploy/kubernetes/helm/sloth/templates/deployment.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom_no_extras.yaml
- deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom_slo_config.yaml
- deploy/kubernetes/helm/sloth/tests/values_test.go
- deploy/kubernetes/helm/sloth/values.yaml
To be able to select a node in kubernetes using nodeSelector property:
- **nodeSelector** is used in a Pod specification (usually within a Deployment, StatefulSet, etc.) to tell the scheduler which nodes are eligible to run the Pod, based on node labels.
> [FEAT] add helm chart nodeselector property

- internal/plugin/slo/contrib/validate_victoria_metrics_v1/README.md
super tiny markdown heading fix so it renders the heading right
> chore: tiny markdown heading fix
