README.md

I was reading through the entire README and found some small typos. Hope this helps :+1:

Some readme suggestions

---

CHANGELOG.md
cmd/sloth/commands/k8scontroller.go
internal/app/kubecontroller/retriever.go
internal/k8sprometheus/kubernetes.go

This will give us the ability to shard Sloth to handle only the part of the Slos we want.

Add label selector to Kubernetes controller

---

README.md

Moar awesome badges! Thanks to @jesusvazquez for the idea!

Add OpenSLO and Kubernetes badges

---

README.md
deploy/kubernetes/kustomization.yaml

This reverts commit 137310561e70183d4c76b1cfe3b3314fc3b4404a, reversing
changes made to 40d714863da95886c0f3cf80b998b1654aaf084d.

Revert "Merge pull request #147 from slok/slok/kustomize"

---

.github/workflows/ci.yaml
Makefile
docker/dev/Dockerfile
docker/prod/Dockerfile

Migrate docker images to ghcr

---

deploy/kubernetes/helm/sloth/Chart.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/cluster_role_binding_custom.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/cluster_role_binding_default.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/cluster_role_custom.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/cluster_role_default.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom_no_extras.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_default.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/pod_monitor_custom.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/pod_monitor_default.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/sa_custom.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/sa_default.yaml
deploy/kubernetes/helm/sloth/values.yaml
deploy/kubernetes/raw/sloth-with-common-plugins.yaml
deploy/kubernetes/raw/sloth.yaml
scripts/deploygen.sh

Migrate to ghcr deployment mechanism

---

CHANGELOG.md
README.md

Add note on docs of ghcr.io migration

---

internal/alert/window.go

Don't fail if the loaded slo period windows is the same, just warn

---

deploy/kubernetes/helm/sloth/Chart.yaml
deploy/kubernetes/helm/sloth/templates/pod-monitor.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/pod_monitor_custom.yaml
deploy/kubernetes/helm/sloth/tests/values_test.go
deploy/kubernetes/helm/sloth/values.yaml
deploy/kubernetes/raw/sloth-with-common-plugins.yaml
deploy/kubernetes/raw/sloth.yaml

Add optional prometheus scrape interval to Helm chart

---

.github/workflows/ci.yaml
.github/workflows/helmrelease.yaml
CHANGELOG.md
README.md
go.mod

Related https://github.com/slok/sloth/issues/547

Update CI and some docs

---

CHANGELOG.md
deploy/kubernetes/helm/sloth/Chart.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_default.yaml
deploy/kubernetes/helm/sloth/values.yaml
deploy/kubernetes/raw/sloth-with-common-plugins.yaml
deploy/kubernetes/raw/sloth.yaml

It was about time for a new Sloth release.

Prepare v0.12.0 release

---

cmd/sloth/commands/generate.go
cmd/sloth/commands/validate.go
internal/storage/io/sloth.go
internal/storage/io/sloth_test.go

Move sloth prom spec loader to storage package

---

cmd/sloth/commands/generate.go
cmd/sloth/commands/validate.go
internal/storage/io/openslo.go
internal/storage/io/openslo_test.go
internal/storage/io/sloth.go
internal/storage/io/sloth_test.go

Move open SLO spec loader to storage package

---

cmd/sloth/commands/k8scontroller.go
internal/app/generate/prometheus.go
internal/app/generate/prometheus_test.go
internal/k8sprometheus/storage.go
internal/k8sprometheus/storage_test.go
internal/storage/io/std_prometheus.go
internal/storage/io/std_prometheus_test.go
internal/storage/k8s/k8s.go
pkg/common/model/slo_prometheus.go

Move apiserver storage to storage package

---

internal/app/generate/process.go
internal/app/generate/process_core.go
internal/app/generate/prometheus.go
internal/app/generate/prometheus_test.go

Add SLO generation as a chain of processors

---

internal/kubernetes/modelmap/slo.go
internal/storage/io/prometheus_operator_test.go
internal/storage/io/std_prometheus.go
internal/storage/io/std_prometheus_test.go
internal/storage/k8s/k8s.go
pkg/common/model/slo_prometheus.go

Add intervals to prom rule models

---

internal/app/generate/generate_test.go

Part of #577 (missed on `git commit add` 🤦)

Add missing SLO plugin unit test usage on domain app

---

CHANGELOG.md
internal/app/generate/generate.go
internal/app/generate/generate_test.go
pkg/common/model/slo_prometheus.go

Add priority to have SLO plugins execution order in the chain

---

internal/app/generate/generate.go
internal/app/generate/process.go
pkg/prometheus/plugin/slo/v1/v1.go

Add the original SLO group source information to the plugin request

---

CHANGELOG.md
cmd/sloth/commands/generate.go
cmd/sloth/commands/k8scontroller.go
internal/app/generate/generate.go
internal/plugin/slo/core/sli_rules_v1/plugin.go
internal/plugin/slo/core/sli_rules_v1/plugin_test.go

Remove not optimized SLI rule generation flag

---

cmd/sloth/commands/generate.go
cmd/sloth/commands/k8scontroller.go
internal/app/generate/generate.go

Pass default plugins as a chain

---

internal/plugin/slo/core/alert_rules_v1/README.md
internal/plugin/slo/core/debug_v1/README.md
internal/plugin/slo/core/metadata_rules_v1/README.md
internal/plugin/slo/core/noop_v1/README.md
internal/plugin/slo/core/sli_rules_v1/README.md
internal/plugin/slo/core/validate_v1/README.md

Add SLO plugin readmes

---

CHANGELOG.md
deploy/kubernetes/helm/sloth/templates/deployment.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom_no_extras.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_custom_slo_config.yaml
deploy/kubernetes/helm/sloth/tests/testdata/output/deployment_default.yaml
deploy/kubernetes/helm/sloth/tests/values_test.go
deploy/kubernetes/helm/sloth/values.yaml
deploy/kubernetes/raw/sloth-with-common-plugins.yaml
deploy/kubernetes/raw/sloth.yaml

Prepare for v0.13.0
